title: "Your Name"
description: "Engineer | Biomechanics | Footwear | Data"
url: "https://lancenicholls.github.io" # update to your custom domain later
theme: null
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

navigation:
  - title: "Projects"
    url: /projects/
  - title: "Resume"
    url: /resume/
  - title: "About"
    url: /about/

collections:
  projects:
    output: true
    permalink: /projects/:title/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: single
      author_profile: false
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false

author:
  name: "Your Name"
  links:
    - label: "GitHub"
      url: "https://github.com/lancenicholls"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/lance-nicholls-0421561b4/"
