title: "Lance Nicholls"
description: "Mechanical Engineering • Biomechanics • Running"
url: "https://YOUR-USERNAME.github.io"   # your user site URL
baseurl: ""                               # <-- IMPORTANT: empty for user sites

theme: null
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: default


markdown: kramdown
kramdown: { input: GFM }
plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives

navigation:
  - title: "Projects"
    url: /projects/
  - title: "Resume"
    url: /resume/
  - title: "About"
    url: /about/

collections:
  projects:
    output: true
    permalink: /projects/:title/

defaults:
  - scope: { path: "", type: "projects" }
    values: { layout: single, author_profile: false }
  - scope: { path: "" }
    values: { layout: single, author_profile: false }

# Build settings
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives

# Author / social (optional)
author:
  name: "Lance Nicholls"
  links:
    - label: "GitHub"
      url: "https://github.com/lancenicholls3"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/lance-nicholls-0421561b4/"

# (Optional) Analytics later:
# google_analytics: G-XXXXXXXX
